version: 2
jobs:
  windows:
    docker:
      - image: cdrx/pyinstaller-windows:python3

    working_directory: ~/PlanarAlly/server

    steps:
      - checkout:
          path: ~/PlanarAlly

      - run:
          name: Build Windows executable
          command: pyinstaller --clean -y --dist ./dist/windows --workpath /tmp *.spec

      - store_artifacts:
          path: ./dist/windows
      
      - persist_to_workspace:
          root: ./
          paths:
            - VERSION
            - ./dist/windows


  
  release:
    docker:
      - image: cibuilds/github:0.12.1
    
    working_directory: /tmp/workspace
    
    steps:
      - attach_workspace:
          at: /tmp/workspace
      
      - run:
          command: ls
      
      - run:
          name: "Publish release on github"
          command: |
            VERSION=$(cat VERSION)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -draft ${VERSION} ./dist/windows/

workflows:
  version: 2
  build:
    jobs:
      - windows:
          filters:
            branches:
              only:
                - dev
                - feature/CircleCI
            tags:
              only: /^\d+\.\d+\.\d+[-a-zA-Z0-9]*$/
      - release:
          requires:
            - windows
          filters:
            branches:
              only: feature/CircleCI
            # tags:
            #   only: /^\d+\.\d+\.\d+[-a-zA-Z0-9]*$/
