version: 2
jobs:
  windows:
    docker:
      - image: cdrx/pyinstaller-windows:python3

    working_directory: ~/PlanarAlly/server

    steps:
      - checkout:
          path: ~/PlanarAlly

      - run:
          name: Build Windows executable
          command: pyinstaller --clean -y --dist ./dist/windows --workpath /tmp *.spec

      - store_artifacts:
          path: ./dist/windows

workflows:
  version: 2
  build:
    jobs:
      - windows:
          filters:
            branches:
              only:
                - master
                - dev
