version: 2
jobs:
  checkout:
    docker:
      - image: circleci/python:3.6.8-node

    steps:
      - checkout:
          path: ~/PlanarAlly

      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/PlanarAlly

  npm-build:
    docker:
      - image: circleci/python:3.6.8-node

    working_directory: ~/PlanarAlly/client

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          name: Restoring repo cache

      - restore_cache:
          key: npm-{{ checksum "package.json" }}
          name: Restoring npm cache

      - run:
          name: npm i
          command: npm i

      - save_cache:
          key: npm-{{ checksum "package.json "}}
          paths:
            - ./node_modules

      - run:
          name: Build production files
          command: npm run build

  windows:
    docker:
      - image: cdrx/pyinstaller-windows:python3

    working_directory: ~/PlanarAlly/server

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Build Windows executable
          command: pyinstaller --clean -y --dist ./dist/windows --workpath /tmp *.spec

      - store_artifacts:
          path: ./dist/windows

  docker:

    docker:
      - image: circleci/python:3.6.8-node

    working_directory: ~/PlanarAlly

    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Build docker image
          command: docker build .

      - run:
          name: Push docker image
          command: docker push

workflows:
  version: 2
  build:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
                - dev
                - feature/CircleCI
      - npm_build:
          requires:
            - checkout
      - windows:
          filters:
            branches:
              only: master
          requires:
            - npm_build
      - docker:
          requires:
            - npm_build
