version: 2
jobs:
  build:
    docker:
      - image: docker:latest

    working_directory: ~/PlanarAlly/server

    steps:
      - checkout:
          path: ~/PlanarAlly

      - run:
          name: Build Windows executable
          command: docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows:python3
